steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "task-manager-backend",
        "--source=.",
        "--platform=managed",
        "--region=us-central1",
        "--allow-unauthenticated",
      ]
