version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=task_manager
